### ISSUE TITLE
v2 Retest Entry misses

### ISSUE THREAD

**Issue by kobyl** [kobyl/bot-issues#1]

**Comment by kobyl** [comment]
![image](https://github.com/kobyl/bot-issues/assets/3729400/cf8241f3-7688-4fe1-9f7e-a664d659b59f)

https://cdn.discordapp.com/attachments/1151313673281863803/1232709206511976468/Screenshot_2024-04-24_100604.png?ex=662a7169&is=66291fe9&hm=9086f08066c3b662a1010735936bbe5ba2ae7acc23f4a364eceaf73ef88da5bc&

Logs:
https://discord.com/channels/1151313671893553254/1151313673281863803/1232709514118168597

**Comment by kobyl** [comment]
I was only entering if candle was entirely outside of box. Should be fixed with 135

**Comment by emulsionla** [comment]
![Screenshot 2024-04-25 093243](https://github.com/kobyl/bot-issues/assets/168107054/c091039b-8b8a-4d8e-a34f-111b60ba9aed)

**Comment by emulsionla** [comment]
Here's 3 missing triangles.  And the logs:

[Uploading NinjaScript Output 4_25_2024 10_36 AM.txt…]()

**Comment by kobyl** [comment]
https://discord.com/channels/1151313671893553254/1151313673281863803/1233881594549501963

**Comment by kobyl** [comment]
Date - 4/25/2023 0753

**Comment by kobyl** [comment]
![image](https://github.com/kobyl/bot-issues/assets/3729400/49873dc8-185d-44e8-ad8a-82e3ccacbf2d)

**Comment by kobyl** [comment]
Was looking for a wick engulf instead of a wick sweep. Also added the double engulf.

**Comment by kobyl** [comment]
Released with 135.
